// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'modules/robotic-nervous-system/README',
        'modules/robotic-nervous-system/ros2-architecture-for-humanoids',
        'modules/robotic-nervous-system/python-agents-and-robot-control',
        'modules/robotic-nervous-system/modeling-the-body-with-urdf',
      ],
    },
  ],
};

module.exports = sidebars;